#!/usr/bin/env python3
"""
VAULT  -  persistent result storage on SQLite.
Credits: @Poriot_ke

The first version stored scans as JSON files and the all-time pool as an
append-only JSONL that was **fully rewritten on every scan** (O(n) per scan, and
the reader silently stopped at the oldest 400k lines). It worked for a demo and
would not survive real use.

SQLite gives, for free:

  * O(1) upserts for the pool (no whole-file rewrite, no unbounded growth),
  * per-country / per-status queries, which is what the UI actually asks for,
  * a proper cap on pool size,
  * multi-thread safety (WAL + a busy timeout) and crash safety.

Tables
------
scans    one row per /mpx run (chat, counts, elapsed, real IP)
records  the individual working proxies of a scan (indexed by scan_id)
pool     every working proxy ever found, deduped by `raw` (fastest wins,
         newest wins a tie)

Geo caching stays a plain JSON file (`geo_cache.json`) — it belongs to geoip.py,
is write-once-read-many, and benefits from being human-inspectable.

Legacy `pool.jsonl` and `scans/<chat>/<scan>.json` files from the JSON version
are imported once on first run and then renamed to `*.migrated`.
"""
from __future__ import annotations

import glob
import json
import os
import re
import sqlite3
import threading
import time

SCAN_INDEX_KEEP = 25           # scans kept per chat (older ones are deleted)
POOL_MAX_UNIQUE = 200_000      # hard cap on distinct proxies in the pool

# scan ids are generated by the bot; anything else (e.g. a crafted
# callback_data) must never be trusted.
SCAN_ID_RE = re.compile(r"^[0-9a-f]{6,32}$")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS scans (
    scan_id  TEXT PRIMARY KEY,
    chat_id  TEXT NOT NULL,
    ts       INTEGER NOT NULL,
    total    INTEGER,
    valid    INTEGER,
    elapsed  REAL,
    real_ip  TEXT,
    meta     TEXT
);
CREATE TABLE IF NOT EXISTS records (
    scan_id TEXT NOT NULL,
    idx     INTEGER,
    raw     TEXT,
    proto   TEXT,
    lat     REAL,
    ip      TEXT,
    st      TEXT,
    cc      TEXT,
    country TEXT,
    sc      INTEGER
);
CREATE INDEX IF NOT EXISTS ix_records_scan ON records(scan_id);
CREATE INDEX IF NOT EXISTS ix_records_cc   ON records(scan_id, cc);
CREATE TABLE IF NOT EXISTS pool (
    raw     TEXT PRIMARY KEY,
    proto   TEXT,
    lat     REAL,
    ip      TEXT,
    st      TEXT,
    cc      TEXT,
    country TEXT,
    sc      INTEGER,
    ts      INTEGER
);
CREATE INDEX IF NOT EXISTS ix_pool_lat ON pool(lat);
CREATE INDEX IF NOT EXISTS ix_pool_cc  ON pool(cc);
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
"""

_RECORD_FIELDS = ("raw", "proto", "lat", "ip", "st", "cc", "country", "sc")
POOL_FIELDS = ("raw", "proto", "lat", "ip", "st", "cc", "country", "sc", "ts")


def valid_scan_id(scan_id) -> bool:
    return bool(isinstance(scan_id, str) and SCAN_ID_RE.match(scan_id))


def _pool_sort_key(row):
    """Fastest first; newest wins a latency tie; then raw for stability."""
    lat = row.get("lat")
    lat = float(lat) if isinstance(lat, (int, float)) else 9e9
    return (lat, -(row.get("ts") or 0), str(row.get("raw", "")))


class Vault:
    def __init__(self, root: str = "vault"):
        self.root = root
        self.db_path = os.path.join(root, "vault.db")
        self.geo_path = os.path.join(root, "geo_cache.json")
        self._local = threading.local()
        # RLock: migration calls push_pool() while the lock is already held
        self._write_lock = threading.RLock()
        os.makedirs(root, exist_ok=True)
        with self._write_lock:
            self._conn().executescript(_SCHEMA)
            self._conn().commit()
            self._migrate_legacy()

    # ------------------------------------------------------------ plumbing --
    def _conn(self) -> sqlite3.Connection:
        conn = getattr(self._local, "conn", None)
        if conn is None:
            conn = sqlite3.connect(self.db_path, timeout=10, isolation_level=None)
            conn.row_factory = sqlite3.Row
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA synchronous=NORMAL")
            conn.execute("PRAGMA busy_timeout=5000")
            self._local.conn = conn
        return conn

    @staticmethod
    def _record_row(r, scan_id, idx):
        if not isinstance(r, dict):
            r = {"raw": str(r)}
        return (scan_id, idx, str(r.get("raw", "")), r.get("proto"), r.get("lat"),
                r.get("ip"), r.get("st"), r.get("cc"), r.get("country"),
                r.get("sc"))

    @staticmethod
    def _row_to_record(row) -> dict:
        out = {k: row[k] for k in _RECORD_FIELDS if k in row.keys()}
        out["raw"] = out.get("raw") or ""
        return out

    # --------------------------------------------------------------- scans --
    def save_scan(self, chat_id, scan_id: str, records: list, meta: dict | None = None):
        """Persist one scan's full result set. Returns the scan id or None."""
        if not valid_scan_id(scan_id):
            return None
        records = records or []
        meta = meta or {}
        now = int(time.time())
        with self._write_lock:
            conn = self._conn()
            conn.execute("BEGIN")
            try:
                conn.execute(
                    "INSERT OR REPLACE INTO scans "
                    "(scan_id, chat_id, ts, total, valid, elapsed, real_ip, meta) "
                    "VALUES (?,?,?,?,?,?,?,?)",
                    (scan_id, str(chat_id), now, meta.get("total"), len(records),
                     meta.get("elapsed"), meta.get("real_ip"),
                     json.dumps(meta, ensure_ascii=False)))
                conn.execute("DELETE FROM records WHERE scan_id=?", (scan_id,))
                conn.executemany(
                    "INSERT INTO records (scan_id, idx, raw, proto, lat, ip, st, cc, "
                    "country, sc) VALUES (?,?,?,?,?,?,?,?,?,?)",
                    [self._record_row(r, scan_id, i) for i, r in enumerate(records)])
                self._prune(conn, str(chat_id))
                conn.execute("COMMIT")
            except Exception:
                conn.execute("ROLLBACK")
                raise
        return scan_id

    def _prune(self, conn, chat_id: str) -> None:
        rows = conn.execute(
            "SELECT scan_id FROM scans WHERE chat_id=? ORDER BY ts DESC, rowid DESC",
            (chat_id,)
        ).fetchall()
        for row in rows[SCAN_INDEX_KEEP:]:
            conn.execute("DELETE FROM records WHERE scan_id=?", (row["scan_id"],))
            conn.execute("DELETE FROM scans WHERE scan_id=?", (row["scan_id"],))

    def load_scan(self, chat_id, scan_id: str):
        if not valid_scan_id(scan_id):
            return None
        conn = self._conn()
        head = conn.execute(
            "SELECT * FROM scans WHERE scan_id=? AND chat_id=?",
            (scan_id, str(chat_id))).fetchone()
        if not head:
            return None
        records = [self._row_to_record(r) for r in conn.execute(
            "SELECT * FROM records WHERE scan_id=? ORDER BY idx", (scan_id,))]
        try:
            meta = json.loads(head["meta"]) if head["meta"] else {}
        except ValueError:
            meta = {}
        return {"scan_id": scan_id, "chat_id": head["chat_id"], "ts": head["ts"],
                "meta": meta, "records": records}

    def list_scans(self, chat_id, limit: int = 10) -> list:
        conn = self._conn()
        out = []
        for row in conn.execute(
                "SELECT * FROM scans WHERE chat_id=? ORDER BY ts DESC, rowid DESC LIMIT ?",
                (str(chat_id), max(1, min(limit, 100)))):
            if not valid_scan_id(row["scan_id"]):
                continue
            counts = {r["cc"] or "ZZ": r["n"] for r in conn.execute(
                "SELECT cc, COUNT(*) AS n FROM records WHERE scan_id=? "
                "GROUP BY cc ORDER BY n DESC", (row["scan_id"],))}
            out.append({"scan_id": row["scan_id"], "ts": row["ts"],
                        "valid": row["valid"], "checked": row["total"],
                        "countries": counts})
        return out

    def update_records(self, scan_id: str, updated: list) -> int:
        """Replace the stored fields of some records (used by re-verify)."""
        if not valid_scan_id(scan_id) or not updated:
            return 0
        with self._write_lock:
            conn = self._conn()
            conn.execute("BEGIN")
            try:
                n = 0
                for r in updated:
                    cur = conn.execute(
                        "UPDATE records SET lat=?, ip=?, st=?, cc=?, country=?, sc=? "
                        "WHERE scan_id=? AND raw=?",
                        (r.get("lat"), r.get("ip"), r.get("st"), r.get("cc"),
                         r.get("country"), r.get("sc"), scan_id, r.get("raw")))
                    n += cur.rowcount or 0
                conn.execute("COMMIT")
                return n
            except Exception:
                conn.execute("ROLLBACK")
                raise

    # ---------------------------------------------------------------- pool --
    def push_pool(self, records: list) -> int:
        """Upsert working proxies into the all-time pool. Returns rows sent."""
        if not records:
            return 0
        now = int(time.time())
        rows = [(str(r.get("raw", "")), r.get("proto"), r.get("lat"), r.get("ip"),
                 r.get("st"), r.get("cc"), r.get("country"), r.get("sc"), now)
                for r in records if r.get("raw")]
        if not rows:
            return 0
        with self._write_lock:
            conn = self._conn()
            conn.execute("BEGIN")
            try:
                # fastest wins; on a tie, the newer observation wins
                conn.executemany(
                    "INSERT INTO pool (raw, proto, lat, ip, st, cc, country, sc, ts) "
                    "VALUES (?,?,?,?,?,?,?,?,?) "
                    "ON CONFLICT(raw) DO UPDATE SET "
                    "  proto=excluded.proto, lat=excluded.lat, ip=excluded.ip, "
                    "  st=excluded.st, cc=excluded.cc, country=excluded.country, "
                    "  sc=excluded.sc, ts=excluded.ts "
                    "WHERE (excluded.lat IS NOT NULL AND "
                    "        (pool.lat IS NULL OR excluded.lat <= pool.lat))",
                    rows)
                conn.execute(
                    "DELETE FROM pool WHERE raw IN ("
                    "  SELECT raw FROM pool ORDER BY "
                    "    CASE WHEN lat IS NULL THEN 1e18 ELSE lat END DESC "
                    "  LIMIT max(0, (SELECT COUNT(*) FROM pool) - ?))",
                    (POOL_MAX_UNIQUE,))
                conn.execute("COMMIT")
            except Exception:
                conn.execute("ROLLBACK")
                raise
        return len(rows)

    def load_pool(self, cc=None) -> list:
        conn = self._conn()
        if cc:
            rows = conn.execute("SELECT * FROM pool WHERE cc=? ORDER BY lat", (cc,))
        else:
            rows = conn.execute("SELECT * FROM pool ORDER BY lat")
        return [{k: row[k] for k in POOL_FIELDS} for row in rows]

    def pool_size(self) -> int:
        return self._conn().execute("SELECT COUNT(*) AS n FROM pool").fetchone()["n"]

    def pool_countries(self) -> dict:
        return {r["cc"] or "ZZ": r["n"] for r in self._conn().execute(
            "SELECT cc, COUNT(*) AS n FROM pool GROUP BY cc ORDER BY n DESC")}

    # ----------------------------------------------------------- migration --
    def _migrate_legacy(self) -> None:
        """One-time import of the JSON/JSONL files written by the old vault."""
        conn = self._conn()
        done = conn.execute("SELECT v FROM meta WHERE k='legacy_migrated'").fetchone()
        if done:
            return
        imported = 0

        legacy_pool = os.path.join(self.root, "pool.jsonl")
        if os.path.isfile(legacy_pool):
            best = {}
            try:
                with open(legacy_pool, "r", encoding="utf-8", errors="ignore") as fh:
                    for line in fh:
                        try:
                            row = json.loads(line)
                        except ValueError:
                            continue
                        if not row.get("raw"):
                            continue
                        prev = best.get(row["raw"])
                        if prev is None or _pool_sort_key(row) <= _pool_sort_key(prev):
                            best[row["raw"]] = row
                if best:
                    self.push_pool(list(best.values()))
                    imported += len(best)
            except OSError:
                pass
            _rename(legacy_pool)

        for path in glob.glob(os.path.join(self.root, "scans", "*", "*.json")):
            if path.endswith("index.json"):
                continue
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
            except (OSError, ValueError):
                continue
            scan_id = data.get("scan_id")
            chat_id = data.get("chat_id")
            records = data.get("records")
            if not (valid_scan_id(scan_id) and chat_id and isinstance(records, list)):
                continue
            try:
                with self._write_lock:
                    conn.execute("BEGIN")
                    try:
                        conn.execute(
                            "INSERT OR REPLACE INTO scans (scan_id, chat_id, ts, total, "
                            "valid, elapsed, real_ip, meta) VALUES (?,?,?,?,?,?,?,?)",
                            (scan_id, str(chat_id), data.get("ts") or int(time.time()),
                             (data.get("meta") or {}).get("total"), len(records),
                             (data.get("meta") or {}).get("elapsed"),
                             (data.get("meta") or {}).get("real_ip"),
                             json.dumps(data.get("meta") or {})))
                        conn.execute("DELETE FROM records WHERE scan_id=?", (scan_id,))
                        conn.executemany(
                            "INSERT INTO records (scan_id, idx, raw, proto, lat, ip, st, cc, "
                            "country, sc) VALUES (?,?,?,?,?,?,?,?,?,?)",
                            [self._record_row(r, scan_id, i) for i, r in enumerate(records)])
                        conn.execute("COMMIT")
                    except Exception as inner:
                        # a half-finished BEGIN would poison the connection for the
                        # whole process (and block every later save_scan)
                        try:
                            conn.execute("ROLLBACK")
                        except Exception:
                            pass
                        print("vault: skipped legacy scan", scan_id, type(inner).__name__)
                        continue
                imported += 1
            except Exception as e:
                print("vault: legacy import failed", type(e).__name__, e)
                continue
            _rename(path)

        conn.execute("INSERT OR REPLACE INTO meta (k, v) VALUES ('legacy_migrated', ?)",
                     (str(int(time.time())),))
        if imported:
            print(f"vault: migrated {imported} legacy item(s) into {self.db_path}")


def _rename(path: str) -> None:
    try:
        os.replace(path, path + ".migrated")
    except OSError:
        pass
